// =====================================================
// PERMISSION CONFIGURATION
// Centralized permission definitions for Tuesday Workspace
// =====================================================

// Account Role Permissions (Organization-wide)
export const ACCOUNT_ROLE_PERMISSIONS = {
  system_admin: {
    label: 'System Admin',
    level: 5,
    canManageUsers: true,
    canManageWorkspaces: true,
    canManageSecurity: true,
    canManageAuthentication: true,
    canManageEntraSettings: true,
    canManageIntegrations: true,
    canManageAllAutomations: true,
    canManagePermissions: true,
    canViewAuditLogs: true,
    canViewAllWorkspaces: true,
    canViewAllWorkboards: true,
    canModifySystemSettings: true,
    canCreateOrganizationAutomations: true,
    canCreateWorkspaceAutomations: true,
    canCreateWorkboardAutomations: true,
    canCreatePersonalAutomations: true,
    automationScope: 'all',
    canViewExecutiveDashboard: true,
  },
  executive: {
    label: 'Executive',
    level: 4,
    canManageUsers: false,
    canManageWorkspaces: false,
    canManageSecurity: false,
    canManageAuthentication: false,
    canManageEntraSettings: false,
    canManageIntegrations: false,
    canManageAllAutomations: false,
    canManagePermissions: false,
    canViewAuditLogs: true,
    canViewAllWorkspaces: true,
    canViewAllWorkboards: true,
    canModifySystemSettings: false,
    canCreateOrganizationAutomations: true,
    canCreateWorkspaceAutomations: true,
    canCreateWorkboardAutomations: true,
    canCreatePersonalAutomations: true,
    automationScope: 'organization',
    canViewExecutiveDashboard: true,
  },
  manager: {
    label: 'Manager',
    level: 3,
    canManageUsers: false,
    canManageWorkspaces: false,
    canManageSecurity: false,
    canManageAuthentication: false,
    canManageEntraSettings: false,
    canManageIntegrations: false,
    canManageAllAutomations: false,
    canManagePermissions: false,
    canViewAuditLogs: false,
    canViewAllWorkspaces: false,
    canViewAllWorkboards: false,
    canModifySystemSettings: false,
    canCreateOrganizationAutomations: false,
    canCreateWorkspaceAutomations: true,
    canCreateWorkboardAutomations: true,
    canCreatePersonalAutomations: true,
    automationScope: 'workspace',
    canViewExecutiveDashboard: false,
  },
  member: {
    label: 'Member',
    level: 2,
    canManageUsers: false,
    canManageWorkspaces: false,
    canManageSecurity: false,
    canManageAuthentication: false,
    canManageEntraSettings: false,
    canManageIntegrations: false,
    canManageAllAutomations: false,
    canManagePermissions: false,
    canViewAuditLogs: false,
    canViewAllWorkspaces: false,
    canViewAllWorkboards: false,
    canModifySystemSettings: false,
    canCreateOrganizationAutomations: false,
    canCreateWorkspaceAutomations: false,
    canCreateWorkboardAutomations: true,
    canCreatePersonalAutomations: true,
    automationScope: 'workboard',
    canViewExecutiveDashboard: false,
  },
  viewer: {
    label: 'Viewer',
    level: 1,
    canManageUsers: false,
    canManageWorkspaces: false,
    canManageSecurity: false,
    canManageAuthentication: false,
    canManageEntraSettings: false,
    canManageIntegrations: false,
    canManageAllAutomations: false,
    canManagePermissions: false,
    canViewAuditLogs: false,
    canViewAllWorkspaces: false,
    canViewAllWorkboards: false,
    canModifySystemSettings: false,
    canCreateOrganizationAutomations: false,
    canCreateWorkspaceAutomations: false,
    canCreateWorkboardAutomations: false,
    canCreatePersonalAutomations: false,
    automationScope: 'none',
    canViewExecutiveDashboard: false,
  },
};

// Workspace Role Permissions
export const WORKSPACE_ROLE_PERMISSIONS = {
  workspace_owner: {
    label: 'Workspace Owner',
    level: 5,
    canManageWorkspace: true,
    canInviteUsers: true,
    canRemoveUsers: true,
    canCreateWorkboards: true,
    canManageWorkspaceSettings: true,
    canAssignWorkspaceRoles: true,
    canConfigurePermissions: true,
    canManageWorkspaceAutomations: true,
    canAccessAllWorkboards: true,
    canManageWorkboardAccess: true,
  },
  workspace_manager: {
    label: 'Workspace Manager',
    level: 4,
    canManageWorkspace: false,
    canInviteUsers: true,
    canRemoveUsers: false,
    canCreateWorkboards: true,
    canManageWorkspaceSettings: false,
    canAssignWorkspaceRoles: false,
    canConfigurePermissions: false,
    canManageWorkspaceAutomations: true,
    canAccessAllWorkboards: true,
    canManageWorkboardAccess: false,
  },
  workspace_member: {
    label: 'Workspace Member',
    level: 3,
    canManageWorkspace: false,
    canInviteUsers: false,
    canRemoveUsers: false,
    canCreateWorkboards: false,
    canManageWorkspaceSettings: false,
    canAssignWorkspaceRoles: false,
    canConfigurePermissions: false,
    canManageWorkspaceAutomations: false,
    canAccessAllWorkboards: false,
    canManageWorkboardAccess: false,
  },
  workspace_viewer: {
    label: 'Workspace Viewer',
    level: 2,
    canManageWorkspace: false,
    canInviteUsers: false,
    canRemoveUsers: false,
    canCreateWorkboards: false,
    canManageWorkspaceSettings: false,
    canAssignWorkspaceRoles: false,
    canConfigurePermissions: false,
    canManageWorkspaceAutomations: false,
    canAccessAllWorkboards: false,
    canManageWorkboardAccess: false,
  },
  workspace_observer: {
    label: 'Workspace Observer',
    level: 2,
    canManageWorkspace: false,
    canInviteUsers: false,
    canRemoveUsers: false,
    canCreateWorkboards: false,
    canManageWorkspaceSettings: false,
    canAssignWorkspaceRoles: false,
    canConfigurePermissions: false,
    canManageWorkspaceAutomations: false,
    canAccessAllWorkboards: false,
    canManageWorkboardAccess: false,
    readOnly: true,
  },
};

// Workboard Role Permissions
export const WORKBOARD_ROLE_PERMISSIONS = {
  workboard_owner: {
    label: 'Workboard Owner',
    level: 5,
    canEdit: true,
    canDelete: true,
    canCreateItems: true,
    canEditItems: true,
    canDeleteItems: true,
    canManageMembers: true,
    canManageSettings: true,
    canManageAccess: true,
    canManageColumns: true,
    canManageGroups: true,
    canManageStatuses: true,
    canManagePriorities: true,
    canChangeVisibility: true,
    canManageBoardAutomations: true,
    canCreateSubItems: true,
    canUploadFiles: true,
    canComment: true,
  },
  workboard_editor: {
    label: 'Workboard Editor',
    level: 4,
    canEdit: true,
    canDelete: false,
    canCreateItems: true,
    canEditItems: true,
    canDeleteItems: false,
    canManageMembers: false,
    canManageSettings: false,
    canManageAccess: false,
    canManageColumns: false,
    canManageGroups: false,
    canManageStatuses: false,
    canManagePriorities: false,
    canChangeVisibility: false,
    canManageBoardAutomations: true,
    canCreateSubItems: true,
    canUploadFiles: true,
    canComment: true,
  },
  workboard_contributor: {
    label: 'Workboard Contributor',
    level: 3,
    canEdit: true,
    canDelete: false,
    canCreateItems: true,
    canEditItems: true,
    canDeleteItems: false,
    canManageMembers: false,
    canManageSettings: false,
    canManageAccess: false,
    canManageColumns: false,
    canManageGroups: false,
    canManageStatuses: false,
    canManagePriorities: false,
    canChangeVisibility: false,
    canManageBoardAutomations: false,
    canCreateSubItems: true,
    canUploadFiles: true,
    canComment: true,
    canEditAssignedItems: true,
    canEditOwnedItems: true,
  },
  assigned_contributor: {
    label: 'Assigned Contributor',
    level: 2,
    canEdit: false,
    canDelete: false,
    canCreateItems: false,
    canEditItems: false,
    canDeleteItems: false,
    canManageMembers: false,
    canManageSettings: false,
    canManageAccess: false,
    canManageColumns: false,
    canManageGroups: false,
    canManageStatuses: false,
    canManagePriorities: false,
    canChangeVisibility: false,
    canManageBoardAutomations: false,
    canCreateSubItems: false,
    canUploadFiles: true,
    canComment: true,
    canEditAssignedItems: true,
    canEditOwnedItems: false,
  },
  workboard_viewer: {
    label: 'Workboard Viewer',
    level: 1,
    canEdit: false,
    canDelete: false,
    canCreateItems: false,
    canEditItems: false,
    canDeleteItems: false,
    canManageMembers: false,
    canManageSettings: false,
    canManageAccess: false,
    canManageColumns: false,
    canManageGroups: false,
    canManageStatuses: false,
    canManagePriorities: false,
    canChangeVisibility: false,
    canManageBoardAutomations: false,
    canCreateSubItems: false,
    canUploadFiles: false,
    canComment: false,
    canEditAssignedItems: false,
    canEditOwnedItems: false,
    readOnly: true,
  },
};

// Helper function to get role by level
export const getRoleByLevel = (permissions, level) => {
  return Object.entries(permissions).find(([_, role]) => role.level === level)?.[1] || null;
};

// Helper function to compare role levels
export const hasHigherOrEqualRole = (permissions, currentRoleKey, requiredRoleKey) => {
  const current = permissions[currentRoleKey];
  const required = permissions[requiredRoleKey];
  if (!current || !required) return false;
  return current.level >= required.level;
};